CREATE TABLE IF NOT EXISTS goal_weight (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_level (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(150) NOT NULL,
wasted_calories INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
first_name VARCHAR(150) NOT NULL,
last_name VARCHAR(150) NOT NULL,
age INTEGER NOT NULL,
weight FLOAT NOT NULL,
height INTEGER NOT NULL,
calories INTEGER NOT NULL,
gender VARCHAR(50) NOT NULL,
activity_id INTEGER,
goal_id INTEGER,
FOREIGN KEY (activity_id) REFERENCES activity_level(id),
FOREIGN KEY (goal_id) REFERENCES goal_weight(id)
);

CREATE TABLE IF NOT EXISTS activity_actions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(150) NOT NULL,
wasted_calories INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS activity(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
action_id INTEGER,
duration INTEGER,
FOREIGN KEY (user_id) REFERENCES user(id),
FOREIGN KEY (action_id) REFERENCES activity_actions(id)
);

CREATE TABLE IF NOT EXISTS products(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(150) NOT NULL,
calories INTEGER NOT NULL,
fat INTEGER NOT NULL,
protein INTEGER NOT NULL,
carbo INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ration(
id INTEGER PRIMARY KEY AUTOINCREMENT,
product_id INTEGER,
user_id INTEGER,
weight INTEGER NOT NULL,
created_at DATE NOT NULL,
FOREIGN KEY (product_id) REFERENCES products(id),
FOREIGN KEY (user_id) REFERENCES users(id)
);
